### PR TITLE
Adding ARM templates for API provisioning

### PR DESCRIPTION
**Pull request by cbrevik**
FAKE-scripts stolen from https://github.com/nikolaia/weather-in-harstad
Thanks goes to @nikolaia! 🎉 

Docs for this + Azure-deploy button + templating for dashboard-deploy to follow in the next PR.

```bash
dotnet tool install fake-cli -g --version 5.1.0
# I had to add ~/.dotnet/tools to PATH in order for fishshell to find fake
fake run build.fsx
fake run provision.fsx appName=nowplayingwhatevername parameterSet=test spotifyApiClientId=something spotifyApiClientSecret=something
```

This will build the app in `/build`, zip to `/artifact`, provision resource group + resources, and deploy the zip.

Known issue: Have to set Spotify id/secret each time, not optimal.

### CODE REVIEW

**Comment by mikaelbr** [comment]
Kind of off topic: Wasn't it previously possible to install tools through extensions to `dotnet`? So you could have "dev dependencies" in package.config/csproj/whatever, and do `dotnet fake`? Did they change that?

**Comment by mikaelbr** [comment]
> Known issue: Have to set Spotify id/secret each time, not optimal.

Ooh. Fsharp implementation of .env ? 😄

**Comment by cbrevik** [comment]
> Kind of off topic: Wasn't it previously possible to install tools through extensions to `dotnet`? So you could have "dev dependencies" in package.config/csproj/whatever, and do `dotnet fake`? Did they change that?

That should still be possible, and is probably a good idea for local development. But, the build-script creates an artifact-folder with both the app-zip, and the provisioning-script. So a CI-server would still have to install `fake-cli` to be able to provision based on a specific build, since the artifact only has the build-output, no csproj etc.

> Ooh. Fsharp implementation of .env ? 😄

Haha, that's pretty cool! I like that idea. Would also work as env-variables on CI probably :D
Still have to support id/secret as parameters in template I think, if it is going to work for Azure-button as well.

**Comment by nikolaia** [comment]
Mmmmm mentions.

Last time I worked on this is was a bit crap because tools could be in a [c/f]sproj, but it didn't make to much sense to have a tool there meant for the entire solution 🤷‍♂.

People used to have a `Tools.csproj` in the solution root to restore tools, but with the `dotnet tools` cmd the new best practice seems to not have tools in a csproj-file. 

I also think that having it in a csproj file doesn't add it to path. That's `dotnet tool` magic, so you would have to provide the full path to use it.

The CI server (or any buildscript) could just provide a --tool-path to prevent a global install:
```
dotnet tool install fake-cli --tool-path ./tools
.\tools\fake <script>
```

**Comment by nikolaia** [comment]
For `.env` like you could always just use the config part of ASP.NET: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?tabs=basicconfiguration&view=aspnetcore-2.2#simple-configuration . It's a separate package and works kinda like the node package `config` on npm: https://www.npmjs.com/package/config

**Comment by cbrevik** [comment]
Awesome, thanks @nikolaia! Guess I should re-write `provision.fsx` to check env for id/secret. That does feel much cleaner, and will also support button-deploy.

**Comment by cbrevik** [comment]
Btw Azure CDN needs to be used for custom domains for static websites (hosted by Blob Storage). But I don't feel like scripting that bit. I think it is out-of-scope as well, and people should probably decide for themselves if they want to use it. So I'll keep that as a manual step.

**Comment by mikaelbr** [comment]
Is this a work in progress? Or are you waiting for my review 😬?

**Comment by cbrevik** [comment]
Sorry, slow to respond. I haven't had a chance to pick this back up yet. There are improvements that could be made, but it's basically ready. I'd rather get this merged before doing more. Review please 💃

**Pull request merged**
